'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Extensification.External.Tests.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;001#1#0#Machine&quot;: [
        '''    {
        '''      &quot;006#0#2#v&quot;: &quot;Version 07.00T&quot;,
        '''      &quot;000#0#1#Type&quot;: &quot;Desktop&quot;,
        '''      &quot;007#0#2#date&quot;: &quot;04/02/01&quot;,
        '''      &quot;004#0#2#serial&quot;: &quot;&lt;superuser required&gt;&quot;,
        '''      &quot;001#1#1#Mobo&quot;: &quot;MSI&quot;,
        '''      &quot;002#0#2#model&quot;: &quot;MS-6712&quot;,
        '''      &quot;003#0#2#v&quot;: &quot;1.0&quot;,
        '''      &quot;005#1#1#BIOS&quot;: &quot;American Megatrends&quot;
        '''    }
        '''  ],
        '''  &quot;000#1#0#System&quot;: [
        '''    {
        '''      &quot;001#1#1#Kernel&quot;: &quot;5.10.0-5-686-pae i686&quot;,
        '''      &quot;002#0#2#bits&quot;: &quot;32&quot;,
        '''      &quot;006#0#2#dm&quot;: &quot;LightDM&quot;,
        '''      &quot;005#1#1#Desktop&quot;: &quot;N/A&quot;,
        '''      &quot;000#0#1#Ho [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property JSON_InxiExample() As String
            Get
                Return ResourceManager.GetString("JSON_InxiExample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [{&quot;000#1#2#id&quot;:1,&quot;001#6#3#appname&quot;:&quot;Treeflex&quot;,&quot;002#0#0#appver&quot;:&quot;9.72&quot;,&quot;003#0#0#released&quot;:&quot;10/11/2018&quot;},
        '''{&quot;000#1#2#id&quot;:2,&quot;001#6#3#appname&quot;:&quot;Transcof&quot;,&quot;002#0#0#appver&quot;:&quot;5.5&quot;,&quot;003#0#0#released&quot;:&quot;2/1/2019&quot;},
        '''{&quot;000#1#2#id&quot;:3,&quot;001#6#3#appname&quot;:&quot;Namfix&quot;,&quot;002#0#0#appver&quot;:&quot;8.2.5&quot;,&quot;003#0#0#released&quot;:&quot;11/8/2018&quot;},
        '''{&quot;000#1#2#id&quot;:4,&quot;001#6#3#appname&quot;:&quot;Y-find&quot;,&quot;002#0#0#appver&quot;:&quot;8.2.5&quot;,&quot;003#0#0#released&quot;:&quot;7/24/2018&quot;},
        '''{&quot;000#1#2#id&quot;:5,&quot;001#6#3#appname&quot;:&quot;Sub-Ex&quot;,&quot;002#0#0#appver&quot;:&quot;4.7.4&quot;,&quot;003#0#0#released&quot;:&quot;6/17/2018&quot;},
        '''{&quot;000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property JSON_PropertyTest1() As String
            Get
                Return ResourceManager.GetString("JSON_PropertyTest1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
